site_name: ARIADNE RI Documentation
site_url: https://ARIADNE-Infrastructure.github.io/docs/
site_author: ARIADNE contributors
site_description:
repo_name: ARIADNE-Infrastructure/docs
repo_url: https://github.com/ARIADNE-Infrastructure/docs
copyright: ARIADNE Research Infrastructure AISBL
theme:
  name: material
  features:
    - navigation.sections    # Groups top-level sections in sidebar
    - navigation.instant     # Faster page transitions
    - navigation.top         # Back-to-top button
markdown_extensions:
  - attr_list


nav:
  - Home: index.md
  - User Guide:
    - Introduction: Portal_User_Guide/Section-1_What.md
    - The Map tool (Where): Portal_User_Guide/Section-2_Map_Where.md
    - Time period (When): Portal_User_Guide/Section-3_Time_period_When.md
    - Resource types (Filter): Portal_User_Guide/Section-4_Resource_type-filter.md
