site_name: ARIADNE RI Documentation
site_url: https://ARIADNE-Infrastructure.github.io/docs/
site_author: ARIADNE contributors
site_description:
repo_name: ARIADNE-Infrastructure/docs
repo_url: https://github.com/ARIADNE-Infrastructure/docs
copyright: ARIADNE Research Infrastructure AISBL
theme:
  name: material
  features:
    - navigation.sections    # Groups top-level sections in sidebar
    - navigation.instant     # Faster page transitions
    - navigation.top         # Back-to-top button
markdown_extensions:
  - attr_list


nav:
  - Home: index.md
  - User Guide:
    - Portal_User_Guide: Portal_User_Guide/Section-1_What.md
    - Overview: Portal_user_Guide/Section-2_Map_Where.md
    - Details: section2/details.md
